---

### Basic Setup

- name: Install Proxmoxer
  pip:
    name: proxmoxer

- name: Ensure user groups exists
  group:
    name: "{{ main_username }}"
    state: present

- name: Add main user
  user:
    name: "{{ main_username }}"
    password: "{{ secret_main_user_pass }}"
    groups:
      - "{{ main_username }}"
    shell: /bin/bash

- name: create main user directories
  file:
    path: /home/{{ main_username }}/{{ item }}
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - docker
    - docker/diun
    - docker/scrutiny

- name: Copy backup scripts
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: +x
  loop:
    - { src: "backup.sh", dest: "/root/backup.sh" }
    - { src: "media_backup.sh", dest: "/home/{{ main_username }}/media_backup.sh" }

### Wireguard
#- name: Install Wireguard
#  include: wireguard.yml

### DIUN
- name: Copy DIUN Config Template
  template:
    src: diun_config.yml.j2
    dest: /home/{{ main_username }}/docker/diun/config.yml
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

### Infrastructure
- name: Set up disks/mounts
  include: disks.yml

- name: Set up containers
  include: infrastructure.yml

- name: Install samba config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
- name: Restart samba
  service:
    name: smbd
    state: restarted

#### NUT

- name: Set Nut Facts
  set_fact:
    install_nut: "{{ install_nut == true }}"

- name: Copy nut folder
  copy:
    src: etc/nut/{{item}}
    dest: /etc/nut/{{item}}
    owner: root
    group: nut
    mode: 0640
  with_items:
    - 'nut.conf'
    - 'ups.conf'
    - 'upsd.conf'
    - 'upsd.users'
  when: install_nut

- name: Copy NUT script
  copy:
    src: nut.sh
    dest: /home/{{main_username}}
    mode: +x
  when: install_nut

- name: Run NUT script
  command: /bin/bash ./nut.sh
  args:
    chdir: /home/{{main_username}}
    creates: /home/{{main_username}}/nut.sh
  when: install_nut

### Cron
- name: "Main User Cronjobs"
  cron:
    user: "{{ main_username }}"
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    weekday: "{{ item.weekday }}"
    state: present
  with_items:
    - { job: "docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run", name: "Scrutiny", hour: "*/6", minute: "0", weekday: "*" }

- name: "Root Cronjobs"
  cron:
    user: root
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    weekday: "{{ item.weekday }}"
    state: present
  loop:
    - { job: "/home/{{ main_username }}/media_backup.sh", name: "Media Backup", hour: "0", minute: "30", weekday: "*" }
